### PR TITLE
Specific context addition

### PR DESCRIPTION
**Pull request by vishal-android-freak**
If this is wrong, please let me know the signification or reason of the getApplicationContext() usage.

### CODE REVIEW

**Comment by the-dagger** [comment]
Sounds reasonable to me.
@grgvineet What do you say?

**Comment by grgvineet** [comment]
Why do you need specific context. As far as it is application context is better than specific context as it does not lead to to memory leaks. For example consider volley, it should be initialized only one time. As you have done here initialized with LoginActivity, so as long as application exist LoginActivity can't be destroyed because Volley holds a reference to it. @the-dagger I don't think this commit should be merged

**Comment by vishal-android-freak** [comment]
Agreed. But volley requests if handled in a singleton class (Eg. the application class) becomes application specific where your point stands valid. For eg. again, LoginActivity's ideal behaviour is expected to occur when the activity is in focus. I don't see a reason why it will work in background or places where specific context will be lost.

**Comment by grgvineet** [comment]
Why do you think specific context is better than application context ? The way we used Volley, initialized object is static , so your LoginActivity instance will never be garbage collected.

**Comment by vishal-android-freak** [comment]
http://stackoverflow.com/questions/7298731/when-to-call-activity-context-or-application-context

Also, I don't know why would you not let garbage collection do it's job. LoginActivity is not a service or a receiver running in the background where it definitely needs the application context.

**Review by grgvineet — CHANGES_REQUESTED** [review]
Ok, was not aware that SuperPrefs is not singleton. But again quoting from the link you posted "You only use getApplicationContext() when you know you need a Context for something that may live longer than any other likely Context you have at your disposal", Polley(Volley) uses static instances and will persist throughout the application runtime and should use application context else instance of LoginActivity will not be garbage collection even after calling finish on that, so change it and I will merge it then.

**Comment by vishal-android-freak** [comment]
Done.

**Comment by grgvineet** [comment]
Can you squash your commits also ?

**Pull request merged**
